version: '3'
services:
  lychee:
    image: <IMAGENAME>
    container_name: lychee
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - lychee
    volumes:
      - config:/var/www/html/data
      - images:/var/www/html/uploads

  db:
    image: mariadb
    container_name: lychee_db
    restart: unless-stopped
    networks:
     - lychee
    volumes:
     - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <YOURSAFEPASSWORD1>
      MYSQL_DATABASE: lychee
      MYSQL_USER: lychee
      MYSQL_PASSWORD: <YOURSAFEPASSWORD2>

networks:
  lychee:

volumes:
  config:
  images:
  db:
