name: Docker Image CI

on:
  push:
    branches: 
      - master


jobs:
  
  check:
    name: Hadolint
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run hadolint
        run: hadolint --ignore DL3003 --ignore DL3018 --ignore SC2016 Dockerfile

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lychee-docker-autobuild:$(date +%s)



